/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clocKtokenSol from "./CLOCKtoken.sol";
export type { clocKtokenSol };
import type * as clockTowerPaymentSol from "./ClockTowerPayment.sol";
export type { clockTowerPaymentSol };
import type * as clockTowerSubscribeSol from "./ClockTowerSubscribe.sol";
export type { clockTowerSubscribeSol };
import type * as clockTowerVerifySol from "./ClockTowerVerify.sol";
export type { clockTowerVerifySol };
