/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ClockTowerVerifyInterface extends utils.Interface {
  functions: {
    "changeAdmin(address)": FunctionFragment;
    "changeSystemFee(uint256)": FunctionFragment;
    "checkIfProvider(bytes32)": FunctionFragment;
    "collectFees()": FunctionFragment;
    "systemFee()": FunctionFragment;
    "systemFeeActivate(bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "changeAdmin"
      | "changeSystemFee"
      | "checkIfProvider"
      | "collectFees"
      | "systemFee"
      | "systemFeeActivate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSystemFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIfProvider",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "systemFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "systemFeeActivate",
    values: [PromiseOrValue<boolean>]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeSystemFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIfProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "systemFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemFeeActivate",
    data: BytesLike
  ): Result;

  events: {
    "Verify(bytes32,address,string,string,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Verify"): EventFragment;
}

export interface VerifyEventObject {
  id: string;
  provider: string;
  domain: string;
  url: string;
  email: string;
  phone: string;
}
export type VerifyEvent = TypedEvent<
  [string, string, string, string, string, string],
  VerifyEventObject
>;

export type VerifyEventFilter = TypedEventFilter<VerifyEvent>;

export interface ClockTowerVerify extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ClockTowerVerifyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkIfProvider(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    systemFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  changeAdmin(
    newAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeSystemFee(
    _fixed_fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkIfProvider(
    id: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  collectFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  systemFee(overrides?: CallOverrides): Promise<BigNumber>;

  systemFeeActivate(
    status: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkIfProvider(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    collectFees(overrides?: CallOverrides): Promise<void>;

    systemFee(overrides?: CallOverrides): Promise<BigNumber>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Verify(bytes32,address,string,string,string,string)"(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      domain?: null,
      url?: null,
      email?: null,
      phone?: null
    ): VerifyEventFilter;
    Verify(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      domain?: null,
      url?: null,
      email?: null,
      phone?: null
    ): VerifyEventFilter;
  };

  estimateGas: {
    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkIfProvider(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    systemFee(overrides?: CallOverrides): Promise<BigNumber>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkIfProvider(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    systemFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
