/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as clocKtokenSol from './CLOCKtoken.sol/index.js';
export { ClockTowerSubscribe__factory } from './ClockTowerSubscribe__factory.js';
export { ClockTowerTimeLibrary__factory } from './ClockTowerTimeLibrary__factory.js';