/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as clocKtokenSol from "./CLOCKtoken.sol";
export * as clocktowerSol from "./Clocktower.sol";
export { ClockTowerLibrary__factory } from "./ClockTowerLibrary__factory";
