/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ClockTowerSubscribe,
  ClockTowerSubscribeInterface,
} from "../../../contracts/ClockTowerVerify.sol/ClockTowerSubscribe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getAccount",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "accountAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "exists",
            type: "bool",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                internalType: "uint16",
                name: "dueDay",
                type: "uint16",
              },
              {
                internalType: "enum ClockTowerSubscribe.Frequency",
                name: "frequency",
                type: "uint8",
              },
              {
                internalType: "enum ClockTowerSubscribe.Status",
                name: "status",
                type: "uint8",
              },
            ],
            internalType: "struct ClockTowerSubscribe.SubIndex[]",
            name: "subscriptions",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                internalType: "uint16",
                name: "dueDay",
                type: "uint16",
              },
              {
                internalType: "enum ClockTowerSubscribe.Frequency",
                name: "frequency",
                type: "uint8",
              },
              {
                internalType: "enum ClockTowerSubscribe.Status",
                name: "status",
                type: "uint8",
              },
            ],
            internalType: "struct ClockTowerSubscribe.SubIndex[]",
            name: "provSubs",
            type: "tuple[]",
          },
        ],
        internalType: "struct ClockTowerSubscribe.Account",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ClockTowerSubscribe__factory {
  static readonly abi = _abi;
  static createInterface(): ClockTowerSubscribeInterface {
    return new utils.Interface(_abi) as ClockTowerSubscribeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClockTowerSubscribe {
    return new Contract(address, _abi, signerOrProvider) as ClockTowerSubscribe;
  }
}
