/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ClockTowerSubscribe {
  export type SubscriptionStruct = {
    id: PromiseOrValue<BytesLike>;
    amount: PromiseOrValue<BigNumberish>;
    provider: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    exists: PromiseOrValue<boolean>;
    cancelled: PromiseOrValue<boolean>;
    frequency: PromiseOrValue<BigNumberish>;
    dueDay: PromiseOrValue<BigNumberish>;
  };

  export type SubscriptionStructOutput = [
    string,
    BigNumber,
    string,
    string,
    boolean,
    boolean,
    number,
    number
  ] & {
    id: string;
    amount: BigNumber;
    provider: string;
    token: string;
    exists: boolean;
    cancelled: boolean;
    frequency: number;
    dueDay: number;
  };

  export type DetailsStruct = {
    domain: PromiseOrValue<string>;
    url: PromiseOrValue<string>;
    email: PromiseOrValue<string>;
    phone: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
  };

  export type DetailsStructOutput = [string, string, string, string, string] & {
    domain: string;
    url: string;
    email: string;
    phone: string;
    description: string;
  };

  export type FeeEstimateStruct = {
    fee: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
  };

  export type FeeEstimateStructOutput = [BigNumber, string] & {
    fee: BigNumber;
    token: string;
  };

  export type SubIndexStruct = {
    id: PromiseOrValue<BytesLike>;
    dueDay: PromiseOrValue<BigNumberish>;
    frequency: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type SubIndexStructOutput = [string, number, number, number] & {
    id: string;
    dueDay: number;
    frequency: number;
    status: number;
  };

  export type AccountStruct = {
    accountAddress: PromiseOrValue<string>;
    exists: PromiseOrValue<boolean>;
    subscriptions: ClockTowerSubscribe.SubIndexStruct[];
    provSubs: ClockTowerSubscribe.SubIndexStruct[];
  };

  export type AccountStructOutput = [
    string,
    boolean,
    ClockTowerSubscribe.SubIndexStructOutput[],
    ClockTowerSubscribe.SubIndexStructOutput[]
  ] & {
    accountAddress: string;
    exists: boolean;
    subscriptions: ClockTowerSubscribe.SubIndexStructOutput[];
    provSubs: ClockTowerSubscribe.SubIndexStructOutput[];
  };

  export type SubViewStruct = {
    subscription: ClockTowerSubscribe.SubscriptionStruct;
    status: PromiseOrValue<BigNumberish>;
    totalSubscribers: PromiseOrValue<BigNumberish>;
  };

  export type SubViewStructOutput = [
    ClockTowerSubscribe.SubscriptionStructOutput,
    number,
    BigNumber
  ] & {
    subscription: ClockTowerSubscribe.SubscriptionStructOutput;
    status: number;
    totalSubscribers: BigNumber;
  };

  export type SubscriberViewStruct = {
    subscriber: PromiseOrValue<string>;
    feeBalance: PromiseOrValue<BigNumberish>;
  };

  export type SubscriberViewStructOutput = [string, BigNumber] & {
    subscriber: string;
    feeBalance: BigNumber;
  };
}

export interface ClockTowerSubscribeInterface extends utils.Interface {
  functions: {
    "accountLookup(uint256)": FunctionFragment;
    "addERC20Contract(address,uint256)": FunctionFragment;
    "callerFee()": FunctionFragment;
    "cancelSubscription((bytes32,uint256,address,address,bool,bool,uint8,uint16))": FunctionFragment;
    "changeAdmin(address)": FunctionFragment;
    "changeCallerFee(uint256)": FunctionFragment;
    "changeMaxRemits(uint256)": FunctionFragment;
    "changeSystemFee(uint256)": FunctionFragment;
    "collectFees()": FunctionFragment;
    "createSubscription(uint256,address,(string,string,string,string,string),uint8,uint16)": FunctionFragment;
    "feeBalance(bytes32,address)": FunctionFragment;
    "feeEstimate()": FunctionFragment;
    "getAccount(address)": FunctionFragment;
    "getAccountSubscriptions(bool,address)": FunctionFragment;
    "getSubByIndex(bytes32,uint8,uint16)": FunctionFragment;
    "getSubscribersById(bytes32)": FunctionFragment;
    "getTotalSubscribers()": FunctionFragment;
    "maxRemits()": FunctionFragment;
    "nextUncheckedDay()": FunctionFragment;
    "remit()": FunctionFragment;
    "removeERC20Contract(address)": FunctionFragment;
    "setExternalCallers(bool)": FunctionFragment;
    "subscribe((bytes32,uint256,address,address,bool,bool,uint8,uint16))": FunctionFragment;
    "systemFee()": FunctionFragment;
    "systemFeeActivate(bool)": FunctionFragment;
    "unsubscribe((bytes32,uint256,address,address,bool,bool,uint8,uint16))": FunctionFragment;
    "unsubscribeByProvider((bytes32,uint256,address,address,bool,bool,uint8,uint16),address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accountLookup"
      | "addERC20Contract"
      | "callerFee"
      | "cancelSubscription"
      | "changeAdmin"
      | "changeCallerFee"
      | "changeMaxRemits"
      | "changeSystemFee"
      | "collectFees"
      | "createSubscription"
      | "feeBalance"
      | "feeEstimate"
      | "getAccount"
      | "getAccountSubscriptions"
      | "getSubByIndex"
      | "getSubscribersById"
      | "getTotalSubscribers"
      | "maxRemits"
      | "nextUncheckedDay"
      | "remit"
      | "removeERC20Contract"
      | "setExternalCallers"
      | "subscribe"
      | "systemFee"
      | "systemFeeActivate"
      | "unsubscribe"
      | "unsubscribeByProvider"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountLookup",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addERC20Contract",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "callerFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [ClockTowerSubscribe.SubscriptionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeCallerFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeMaxRemits",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSystemFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      ClockTowerSubscribe.DetailsStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBalance",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "feeEstimate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountSubscriptions",
    values: [PromiseOrValue<boolean>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubByIndex",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscribersById",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSubscribers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxRemits", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextUncheckedDay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "remit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeERC20Contract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setExternalCallers",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [ClockTowerSubscribe.SubscriptionStruct]
  ): string;
  encodeFunctionData(functionFragment: "systemFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "systemFeeActivate",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [ClockTowerSubscribe.SubscriptionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribeByProvider",
    values: [ClockTowerSubscribe.SubscriptionStruct, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addERC20Contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callerFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeCallerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMaxRemits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeSystemFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeEstimate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscribersById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSubscribers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxRemits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextUncheckedDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "remit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeERC20Contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExternalCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "systemFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemFeeActivate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribeByProvider",
    data: BytesLike
  ): Result;

  events: {
    "CallerLog(uint40,uint40,address,bool)": EventFragment;
    "DetailsLog(bytes32,address,uint256,string,string,string,string,string)": EventFragment;
    "ProviderLog(bytes32,address,uint40,uint256,uint8)": EventFragment;
    "SubscriberLog(bytes32,address,uint40,uint256,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallerLog"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DetailsLog"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderLog"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubscriberLog"): EventFragment;
}

export interface CallerLogEventObject {
  timestamp: number;
  checkedDay: number;
  caller: string;
  isFinished: boolean;
}
export type CallerLogEvent = TypedEvent<
  [number, number, string, boolean],
  CallerLogEventObject
>;

export type CallerLogEventFilter = TypedEventFilter<CallerLogEvent>;

export interface DetailsLogEventObject {
  id: string;
  provider: string;
  timestamp: BigNumber;
  domain: string;
  url: string;
  email: string;
  phone: string;
  description: string;
}
export type DetailsLogEvent = TypedEvent<
  [string, string, BigNumber, string, string, string, string, string],
  DetailsLogEventObject
>;

export type DetailsLogEventFilter = TypedEventFilter<DetailsLogEvent>;

export interface ProviderLogEventObject {
  id: string;
  provider: string;
  timestamp: number;
  amount: BigNumber;
  provEvent: number;
}
export type ProviderLogEvent = TypedEvent<
  [string, string, number, BigNumber, number],
  ProviderLogEventObject
>;

export type ProviderLogEventFilter = TypedEventFilter<ProviderLogEvent>;

export interface SubscriberLogEventObject {
  id: string;
  subscriber: string;
  timestamp: number;
  amount: BigNumber;
  subEvent: number;
}
export type SubscriberLogEvent = TypedEvent<
  [string, string, number, BigNumber, number],
  SubscriberLogEventObject
>;

export type SubscriberLogEventFilter = TypedEventFilter<SubscriberLogEvent>;

export interface ClockTowerSubscribe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ClockTowerSubscribeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    addERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      minimum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callerFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    cancelSubscription(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeCallerFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeMaxRemits(
      _maxRemits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createSubscription(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      details: ClockTowerSubscribe.DetailsStruct,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeBalance(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    feeEstimate(
      overrides?: CallOverrides
    ): Promise<[ClockTowerSubscribe.FeeEstimateStructOutput[]]>;

    getAccount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[ClockTowerSubscribe.AccountStructOutput]>;

    getAccountSubscriptions(
      bySubscriber: PromiseOrValue<boolean>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[ClockTowerSubscribe.SubViewStructOutput[]]>;

    getSubByIndex(
      id: PromiseOrValue<BytesLike>,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [ClockTowerSubscribe.SubscriptionStructOutput] & {
        subscription: ClockTowerSubscribe.SubscriptionStructOutput;
      }
    >;

    getSubscribersById(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClockTowerSubscribe.SubscriberViewStructOutput[]]>;

    getTotalSubscribers(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxRemits(overrides?: CallOverrides): Promise<[BigNumber]>;

    nextUncheckedDay(overrides?: CallOverrides): Promise<[number]>;

    remit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setExternalCallers(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    systemFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unsubscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unsubscribeByProvider(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      subscriber: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  accountLookup(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  addERC20Contract(
    erc20Contract: PromiseOrValue<string>,
    minimum: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callerFee(overrides?: CallOverrides): Promise<BigNumber>;

  cancelSubscription(
    subscription: ClockTowerSubscribe.SubscriptionStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeAdmin(
    newAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeCallerFee(
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeMaxRemits(
    _maxRemits: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeSystemFee(
    _fixed_fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createSubscription(
    amount: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    details: ClockTowerSubscribe.DetailsStruct,
    frequency: PromiseOrValue<BigNumberish>,
    dueDay: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeBalance(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  feeEstimate(
    overrides?: CallOverrides
  ): Promise<ClockTowerSubscribe.FeeEstimateStructOutput[]>;

  getAccount(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ClockTowerSubscribe.AccountStructOutput>;

  getAccountSubscriptions(
    bySubscriber: PromiseOrValue<boolean>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ClockTowerSubscribe.SubViewStructOutput[]>;

  getSubByIndex(
    id: PromiseOrValue<BytesLike>,
    frequency: PromiseOrValue<BigNumberish>,
    dueDay: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClockTowerSubscribe.SubscriptionStructOutput>;

  getSubscribersById(
    id: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClockTowerSubscribe.SubscriberViewStructOutput[]>;

  getTotalSubscribers(overrides?: CallOverrides): Promise<BigNumber>;

  maxRemits(overrides?: CallOverrides): Promise<BigNumber>;

  nextUncheckedDay(overrides?: CallOverrides): Promise<number>;

  remit(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeERC20Contract(
    erc20Contract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setExternalCallers(
    status: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribe(
    subscription: ClockTowerSubscribe.SubscriptionStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  systemFee(overrides?: CallOverrides): Promise<BigNumber>;

  systemFeeActivate(
    status: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unsubscribe(
    subscription: ClockTowerSubscribe.SubscriptionStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unsubscribeByProvider(
    subscription: ClockTowerSubscribe.SubscriptionStruct,
    subscriber: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accountLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    addERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      minimum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    callerFee(overrides?: CallOverrides): Promise<BigNumber>;

    cancelSubscription(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeCallerFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeMaxRemits(
      _maxRemits: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    collectFees(overrides?: CallOverrides): Promise<void>;

    createSubscription(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      details: ClockTowerSubscribe.DetailsStruct,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    feeBalance(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeEstimate(
      overrides?: CallOverrides
    ): Promise<ClockTowerSubscribe.FeeEstimateStructOutput[]>;

    getAccount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ClockTowerSubscribe.AccountStructOutput>;

    getAccountSubscriptions(
      bySubscriber: PromiseOrValue<boolean>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ClockTowerSubscribe.SubViewStructOutput[]>;

    getSubByIndex(
      id: PromiseOrValue<BytesLike>,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClockTowerSubscribe.SubscriptionStructOutput>;

    getSubscribersById(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClockTowerSubscribe.SubscriberViewStructOutput[]>;

    getTotalSubscribers(overrides?: CallOverrides): Promise<BigNumber>;

    maxRemits(overrides?: CallOverrides): Promise<BigNumber>;

    nextUncheckedDay(overrides?: CallOverrides): Promise<number>;

    remit(overrides?: CallOverrides): Promise<void>;

    removeERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setExternalCallers(
      status: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    systemFee(overrides?: CallOverrides): Promise<BigNumber>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    unsubscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    unsubscribeByProvider(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      subscriber: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CallerLog(uint40,uint40,address,bool)"(
      timestamp?: null,
      checkedDay?: null,
      caller?: PromiseOrValue<string> | null,
      isFinished?: null
    ): CallerLogEventFilter;
    CallerLog(
      timestamp?: null,
      checkedDay?: null,
      caller?: PromiseOrValue<string> | null,
      isFinished?: null
    ): CallerLogEventFilter;

    "DetailsLog(bytes32,address,uint256,string,string,string,string,string)"(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      timestamp?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      url?: null,
      email?: null,
      phone?: null,
      description?: null
    ): DetailsLogEventFilter;
    DetailsLog(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      timestamp?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      url?: null,
      email?: null,
      phone?: null,
      description?: null
    ): DetailsLogEventFilter;

    "ProviderLog(bytes32,address,uint40,uint256,uint8)"(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      timestamp?: null,
      amount?: null,
      provEvent?: PromiseOrValue<BigNumberish> | null
    ): ProviderLogEventFilter;
    ProviderLog(
      id?: PromiseOrValue<BytesLike> | null,
      provider?: PromiseOrValue<string> | null,
      timestamp?: null,
      amount?: null,
      provEvent?: PromiseOrValue<BigNumberish> | null
    ): ProviderLogEventFilter;

    "SubscriberLog(bytes32,address,uint40,uint256,uint8)"(
      id?: PromiseOrValue<BytesLike> | null,
      subscriber?: PromiseOrValue<string> | null,
      timestamp?: null,
      amount?: null,
      subEvent?: PromiseOrValue<BigNumberish> | null
    ): SubscriberLogEventFilter;
    SubscriberLog(
      id?: PromiseOrValue<BytesLike> | null,
      subscriber?: PromiseOrValue<string> | null,
      timestamp?: null,
      amount?: null,
      subEvent?: PromiseOrValue<BigNumberish> | null
    ): SubscriberLogEventFilter;
  };

  estimateGas: {
    accountLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      minimum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callerFee(overrides?: CallOverrides): Promise<BigNumber>;

    cancelSubscription(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeCallerFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeMaxRemits(
      _maxRemits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createSubscription(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      details: ClockTowerSubscribe.DetailsStruct,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeBalance(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeEstimate(overrides?: CallOverrides): Promise<BigNumber>;

    getAccount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountSubscriptions(
      bySubscriber: PromiseOrValue<boolean>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSubByIndex(
      id: PromiseOrValue<BytesLike>,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSubscribersById(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSubscribers(overrides?: CallOverrides): Promise<BigNumber>;

    maxRemits(overrides?: CallOverrides): Promise<BigNumber>;

    nextUncheckedDay(overrides?: CallOverrides): Promise<BigNumber>;

    remit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setExternalCallers(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    systemFee(overrides?: CallOverrides): Promise<BigNumber>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unsubscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unsubscribeByProvider(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      subscriber: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      minimum: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callerFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelSubscription(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeAdmin(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeCallerFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeMaxRemits(
      _maxRemits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeSystemFee(
      _fixed_fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createSubscription(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      details: ClockTowerSubscribe.DetailsStruct,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeBalance(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeEstimate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountSubscriptions(
      bySubscriber: PromiseOrValue<boolean>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubByIndex(
      id: PromiseOrValue<BytesLike>,
      frequency: PromiseOrValue<BigNumberish>,
      dueDay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscribersById(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSubscribers(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxRemits(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextUncheckedDay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeERC20Contract(
      erc20Contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setExternalCallers(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    systemFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    systemFeeActivate(
      status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unsubscribe(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unsubscribeByProvider(
      subscription: ClockTowerSubscribe.SubscriptionStruct,
      subscriber: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
